package com.vandunxg.file_processing.auth.domain.model;

public enum OperationType {
  CREATE,
  UPDATE,
  DELETE,
  ACTIVATED,
  DEACTIVATED,
  USER_REGISTERED,
  ADMIN_BOOTSTRAPPED,
  EMAIL_VERIFICATION_REQUESTED,
  EMAIL_VERIFIED,
  PASSWORD_CHANGED,
  PASSWORD_RESET_REQUESTED,
  PASSWORD_RESET_COMPLETED,
  LOGIN_SUCCEEDED,
  LOGIN_FAILED,
  ACCOUNT_LOCKED_OUT,
  TOKEN_REFRESHED,
  TOKEN_REUSE_DETECTED,
  LOGOUT,
  SESSION_REVOKED,
  ALL_SESSIONS_REVOKED
}
