spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/file_processing}
    username: ${DB_USERNAME:file_processing_user}
    password: ${DB_PASSWORD:file_processing_password}

    hikari:
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
      maximum-pool-size: ${DB_POOL_MAX_SIZE:5}
      leak-detection-threshold: 60000

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    from: ${MAIL_FROM:no-reply@file-processing.local}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:false}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:false}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: false

  flyway:
    enabled: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  rabbitmq:
    enable: true

  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_param

server:
  port: ${SERVER_PORT:8080}

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    com.vandunxg.file_processing: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

    org.hibernate.SQL: DEBUG
