package com.vandunxg.file_processing.fileimport.domain.exception;

/** Business rules enforced by the processing-job aggregate. */
public enum ProcessingJobRule {
  ONLY_QUEUED_JOB_CAN_BE_CLAIMED,
  ONLY_QUEUED_JOB_CAN_BE_CANCELLED,
  JOB_NOT_CANCELLABLE,
  JOB_NOT_RETRYABLE,
  RETRY_LIMIT_EXCEEDED,
  ONLY_PROCESSING_JOB_CAN_COMPLETE,
  ONLY_RUNNING_JOB_CAN_RECORD_PROGRESS,
  ONLY_RUNNING_JOB_CAN_FAIL,
  CANCELLATION_MUST_BE_REQUESTED_FIRST,
  PROGRESS_CANNOT_DECREASE,
  INVALID_COUNTERS,
  REPORT_AVAILABILITY_MISMATCH
}
